### ISSUE TITLE
Sometimes the demo works, sometimes it does not.

### ISSUE THREAD

**Issue by eltoroit** [pozil/pub-sub-api-node-client#18]
Hi,

This is a very strange error, I copied the demo in the README file and executed it against a scratch org. I ran it 3 consecutive times and it worked only one time.

This is the result when it **DOES** work:

```
aperez */GitHub/gRPC/PubSub [BuildingDemo] $ npm run original

> pubsub-demo@1.0.0 original
> node pubSubClientOriginal.js

Connected to Salesforce org https://platform-dream-3455-dev-ed.scratch.my.salesforce.com as test-wm37brzzizwl@example.com
Connected to Pub/Sub API endpoint api.pubsub.salesforce.com:7443
Topic schema loaded: /event/CloudNews__e
Subscribe request sent for 1 events from /data/AccountChangeEvent...
^C
```

This is the result when it **DOES NOT** work:

```
aperez */GitHub/gRPC/PubSub [BuildingDemo] $ npm run original

> pubsub-demo@1.0.0 original
> node pubSubClientOriginal.js

Connected to Salesforce org https://platform-dream-3455-dev-ed.scratch.my.salesforce.com as test-wm37brzzizwl@example.com
Connected to Pub/Sub API endpoint api.pubsub.salesforce.com:7443
```

Notice that when it does not work, there are no errors... it seems like it's not waiting or a promise that gets resolved too soon. I tried looking inside the module but I could not see anything obvious.

In the meantime, I have rewritten the demo to add a pause at line 15 which seems to fix the problem (it has not failed again) and to resubscribe after the last request is received

```
import PubSubApiClient from "salesforce-pubsub-api-client";

async function run() {
	let client;

	const initializeClient = async () => {
		client = new PubSubApiClient();
		await client.connect();
	};

	const subscribe = async (channel) => {
		return new Promise(async (resolve, reject) => {
			let promise = client.subscribe(channel, 1);
			// This wait seems to solve a synchronization problem
			await new Promise((resolve2) => setTimeout(resolve2, 1e2));
			promise
				.then((listener) => {
					listener.on("data", (event) => {
						console.log("Received event");
					});
					listener.on("lastevent", (event) => {
						console.log(`Reached last requested event on channel ${listener.getTopicName()}.`);
						resolve();
					});
				})
				.catch((error) => {
					console.error(error);
					console.log("ABORTED");
					reject(error);
				});
		});
	};

	try {
		let channel;
		// channel = "/event/CloudNews__e";
		channel = "/data/AccountChangeEvent";

		await initializeClient();
		while (true) {
			await subscribe(channel);
		}
	} catch (error) {
		console.error(error);
		console.log("ABORTED");
	}
}

run();
```

**Comment by pozil** [comment]
Thanks for reporting this @eltoroit. I never needed this wait statement there before so it took me a number of tries to reproduce and figure out the issue. I believe that the problem started after a `@grpc/grpc-js` patch update (`1.9.0` to `1.9.5`).
I rolled back the grpc client update and it seems to behave fine like it used to. Can you confirm that this is fixed in the latest client versions that I just released (`3.0.2`)?

**Comment by eltoroit** [comment]
Thanks @pozil, for looking into this on a weekend :-)

Unfortunately, it did not fix the original problem, and it also created a different problem.

So, let's talk about the original problem...

1. This is the `package.json` file I am using

```
{
	"name": "pubsub-demo",
	"version": "1.0.0",
	"main": "pubSubClient.js",
	"author": "Andres Perez <aperez@salesforce.com> (http://eltoro.it/)",
	"license": "ISC",
	"type": "module",
	"description": "",
	"scripts": {
		"client": "node pubSubClient.js",
		"original": "node pubSubClientOriginal.js"
	},
	"dependencies": {
		"salesforce-pubsub-api-client": "^3.0.2"
	}
}
```

2. I re-copied the sample from the readme
3. I executed `npm run original` three times, the first two worked, but the last one just output this:

```
aperez */GitHub/gRPC/PubSub [BuildingDemo] $ npm run original

> pubsub-demo@1.0.0 original
> node pubSubClientOriginal.js

Connected to Salesforce org https://connect-energy-4573-dev-ed.scratch.my.salesforce.com as test-5mxbvjtwsu8s@example.com
Connected to Pub/Sub API endpoint api.pubsub.salesforce.com:7443
aperez */GitHub/gRPC/PubSub [BuildingDemo] $ 
```

Now, for the second problem (which may be related) when it executes successfully I get this output (do not worry about the event data, that is correct)

```
aperez */GitHub/gRPC/PubSub [BuildingDemo] $ npm run original

> pubsub-demo@1.0.0 original
> node pubSubClientOriginal.js

Connected to Salesforce org https://connect-energy-4573-dev-ed.scratch.my.salesforce.com as test-5mxbvjtwsu8s@example.com
Connected to Pub/Sub API endpoint api.pubsub.salesforce.com:7443
Topic schema loaded: /data/AccountChangeEvent
Subscribe request sent for 1 events from /data/AccountChangeEvent...
Received 1 events, latest replay ID: 3721989
{
  replayId: 3721989,
  payload: AccountChangeEvent {
    ChangeEventHeader: ChangeEventHeader {
      entityName: 'Account',
      recordIds: [Array],
      changeType: 'CREATE',
      changeOrigin: 'com/salesforce/api/rest/58.0;client=postman',
      transactionKey: '00009725-7dac-b8cb-77cf-f901e4259bfd',
      sequenceNumber: 1,
      commitTimestamp: 1696771015000,
      commitNumber: 760877185745,
      commitUser: '00503000004qZePAAU',
      nulledFields: [],
      diffFields: [],
      changedFields: []
    },
    Name: 'ELTORO.IT',
    Type: null,
    ParentId: null,
    BillingAddress: null,
    ShippingAddress: null,
    Phone: null,
    Fax: null,
    AccountNumber: null,
    Website: null,
    Sic: null,
    Industry: null,
    AnnualRevenue: null,
    NumberOfEmployees: null,
    Ownership: null,
    TickerSymbol: null,
    Description: null,
    Rating: null,
    Site: 'ChangeDataCapture Demo',
    OwnerId: '00503000004qZePAAU',
    CreatedDate: 1696771015000,
    CreatedById: '00503000004qZePAAU',
    LastModifiedDate: 1696771015000,
    LastModifiedById: '00503000004qZePAAU',
    Jigsaw: null,
    JigsawCompanyId: null,
    CleanStatus: 'Pending',
    AccountSource: null,
    DunsNumber: null,
    Tradestyle: null,
    NaicsCode: null,
    NaicsDesc: null,
    YearStarted: null,
    SicDesc: null,
    DandbCompanyId: null,
    OperatingHoursId: null
  }
}
Handling Account change event with ID 3721989 on channel /data/AccountChangeEvent (1/1 events received so far)
{
  "replayId": 3721989,
  "payload": {
    "ChangeEventHeader": {
      "entityName": "Account",
      "recordIds": [
        "00103000013ITAqAAO"
      ],
      "changeType": "CREATE",
      "changeOrigin": "com/salesforce/api/rest/58.0;client=postman",
      "transactionKey": "00009725-7dac-b8cb-77cf-f901e4259bfd",
      "sequenceNumber": 1,
      "commitTimestamp": 1696771015000,
      "commitNumber": 760877185745,
      "commitUser": "00503000004qZePAAU",
      "nulledFields": [],
      "diffFields": [],
      "changedFields": []
    },
    "Name": "ELTORO.IT",
    "Type": null,
    "ParentId": null,
    "BillingAddress": null,
    "ShippingAddress": null,
    "Phone": null,
    "Fax": null,
    "AccountNumber": null,
    "Website": null,
    "Sic": null,
    "Industry": null,
    "AnnualRevenue": null,
    "NumberOfEmployees": null,
    "Ownership": null,
    "TickerSymbol": null,
    "Description": null,
    "Rating": null,
    "Site": "ChangeDataCapture Demo",
    "OwnerId": "00503000004qZePAAU",
    "CreatedDate": 1696771015000,
    "CreatedById": "00503000004qZePAAU",
    "LastModifiedDate": 1696771015000,
    "LastModifiedById": "00503000004qZePAAU",
    "Jigsaw": null,
    "JigsawCompanyId": null,
    "CleanStatus": "Pending",
    "AccountSource": null,
    "DunsNumber": null,
    "Tradestyle": null,
    "NaicsCode": null,
    "NaicsDesc": null,
    "YearStarted": null,
    "SicDesc": null,
    "DandbCompanyId": null,
    "OperatingHoursId": null
  }
}
Reached last requested event on channel /data/AccountChangeEvent.
```

and it just hangs... It will not receive new events and it does not exit the application.

**Comment by eltoroit** [comment]
I actually noticed my hack was not working as expected, so I have updated it... The new hack is this:

```
import PubSubApiClient from "salesforce-pubsub-api-client";

async function run() {
	let client;
	// let events = {};
	// let lastReplayId = 0;

	const initializeClient = async () => {
		client = new PubSubApiClient();
		await client.connect();
	};

	const subscribe = async (channel) => {
		console.log(`${new Date().toJSON()} Subscribing`);
		let subscriberPromise = new Promise((resolve2, reject2) => {
			// let promise = client.subscribeFromReplayId(channel, 2, lastReplayId);
			let listenerPromise = client.subscribe(channel, 1);
			listenerPromise
				.then((listener) => {
					listener.on("data", (event) => {
						// lastReplayId = Math.max(lastReplayId, event.replayId);
						// events[event.replayId] = event;
					});
					listener.on("lastevent", (event) => {
						// console.log(`Received ${Object.keys(events).length} event`);
						console.log(`Reached last requested event on channel ${listener.getTopicName()}.`);
						resolve2();
						abortHack();
					});
				})
				.catch((error) => {
					console.error(error);
					console.log("ABORTED");
					reject2(error);
				});
		});

		// This wait seems to solve a synchronization problem
		let forceTimer;
		let promises = [];
		let forceTimerResolve;
		const abortHack = () => {
			if (forceTimerResolve) {
				clearTimeout(forceTimer);
				forceTimerResolve();
				console.log(`${new Date().toJSON()} Hack aborted`);
			}
		};
		let timerPromise = new Promise((resolve2, reject2) => {
			forceTimerResolve = resolve2;
			forceTimer = setTimeout(() => {
				forceTimerResolve = null;
				console.log(`${new Date().toJSON()} Hack ended`);
				resolve2();
			}, 5e3);
		});
		promises.push(subscriberPromise);
		promises.push(timerPromise);
		await Promise.allSettled(promises);
	};

	try {
		let channel = "/event/CloudNews__e";
		// let channel = "/data/AccountChangeEvent";

		await initializeClient();
		while (true) {
			await subscribe(channel);
		}
	} catch (error) {
		console.error(error);
		console.log("ABORTED");
	}
}

run();
```

**Comment by pozil** [comment]
I'll close this issue as there's been a number of changes to the client since then and I believe that we're in a pretty stable state now. Let me know if you still have issues with the latest version.
